#!/bin/bash

HOST_NAME=$1
PASSWORD=$2

sudo -u postgres psql -c "CREATE USER ${HOST_NAME} WITH PASSWORD '${PASSWORD}'; CREATE DATABASE ${HOST_NAME}_db; GRANT ALL PRIVILEGES ON DATABASE ${HOST_NAME}_db TO ${HOST_NAME};"
